<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>

    <title>Welcome to UMI.Framework | Installation</title>

    <link rel="stylesheet" type="text/css" href="/css/normalize.min.css"/>
    <link rel="stylesheet" type="text/css" href="/css/foundation.min.css"/>
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <script src="/js/vendor/custom.modernizr.js"></script>
    <script type="text/javascript" src="/js/vendor/jquery.js"></script>
</head>
<body>
<div class="row">
    <div class="large-12 columns">
        <div class="row">
            <div class="large-12 columns">

                <nav class="top-bar">
                    <ul class="title-area">
                        <li class="name">
                            <h1><a href="#">UMI.Framework Installation</a></h1>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>

        <div class="row" style="margin-top: 25px">
            <div class="columns large-12">
                <?= $content; ?>
            </div>
        </div>

        <footer class="row">
            <div class="large-12 columns">
                <hr/>
                <div class="row">
                    <div class="small-offset-6 small-6 columns text-right">
                        <small>&copy; Umisoft ltd. 2007-2013</small>
                    </div>
                </div>
            </div>
        </footer>

    </div>
</div>
<script type="text/javascript" src="/js/foundation.min.js"></script>
<script type="text/javascript">$(document).foundation();</script>
</body>
</html>