<div class="row">
    <div class="small-3 columns">
        <label for="right-label" class="right inline"><?= $this->translate($element->getLabel()) ?></label>
    </div>
    <div class="small-9 columns <?= !$element->isValid() ? 'error' : '' ?>">
        <?=
        $this->form()
            ->formElement($element) ?>
        <?php if (!$element->isValid()) : ?>
            <small class="error"><?= $this->translate("Invalid element value") ?></small>
        <?php endif; ?>
    </div>
</div>